stages:
- name: Redis
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-redis
      version: 9.0.2
      answers:
        cluster.slaveCount: "2"
        master.persistence.enabled: "true"
        slave.persistence.enabled: "true"
      name: redis
      targetNamespace: api
- name: Ui
  steps:
  - applyYamlConfig:
      path: ./app/ui.yaml
- name: Config
  steps:
  - applyYamlConfig:
      path: ./config.yaml
- name: MicroRpc
  steps:
  - applyYamlConfig:
      path: ./app/micro-rpc.yaml
- name: MicroApi
  steps:
  - applyYamlConfig:
      path: ./app/micro-api.yaml
- name: User
  steps:
  - applyYamlConfig:
      path: ./app/user.yaml
- name: UserApi
  steps:
  - applyYamlConfig:
      path: ./app/user-api.yaml
- name: Pay
  steps:
  - applyYamlConfig:
      path: ./app/pay.yaml
- name: PayApi
  steps:
  - applyYamlConfig:
      path: ./app/pay-api.yaml
notification: {}
