# 负载均衡
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: micro-rpc
  namespace: lecex
spec:
  rules:
  - host: xip.io
    http:
      paths:
        - backend:
            serviceName: app
            servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  namespace: lecex
spec:
  rules:
  - host: xip.io
    http:
      paths:
        - backend:
            serviceName: app
            servicePort: http
---
kind: Service
apiVersion: v1
metadata:
  name: app
  namespace: lecex
spec:
  selector:
    app: app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: lecex
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: lecex/app
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
