apiVersion: v1
kind: Service
metadata:
  name: device
  namespace: lecex
spec:
  selector:
    app: device
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device
  namespace: lecex
  labels:
    app: device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device
  template:
    metadata:
      labels:
        app: device
    spec:
      serviceAccountName: micro-services
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: device
          image: lecex/device
          imagePullPolicy: Always
          command: [
            "device",
            "--server_address=:8080",
          ]
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: DB_HOST
              value: "mariadb-device"
            - name: DB_USER
              value: "root"
            - name: DB_NAME
              value: "device"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-root-password
                  name: mariadb-device
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        - name: health
          image: microhq/health:kubernetes
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=device",
            "--server_address=0.0.0.0:8080"
          ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
