apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: lecex
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: registry.cn-hangzhou.aliyuncs.com/lecex/user
          imagePullPolicy: Always
          command: [
            "user",
            "--server_address=:8080",
          ]
          env:
            - name: MICRO_REGISTRY
              valueFrom:
                  configMapKeyRef:
                    key: registry
                    name: lecex
            - name: MICRO_REGISTRY_ADDRESS
              valueFrom:
                  configMapKeyRef:
                    key: registry-address
                    name: lecex
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: admin-password
                  name: lecex
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  key: app-key
                  name: lecex
            - name: TOKEN_VALIDITY_PERIOD
              value: "15"
            - name: DB_HOST
              value: "mariadb-user"
            - name: DB_USER
              value: "root"
            - name: DB_NAME
              value: "user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-root-password
                  name: mariadb-user
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        - name: health
          image: microhq/health:kubernetes
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=user",
            "--server_address=0.0.0.0:8080"
          ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
