stages:
- name: App
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:github-redis
      version: 10.5.7
      answers:
        cluster.slaveCount: "3"
      name: redis
      targetNamespace: lecex
  - applyAppConfig:
      catalogTemplate: cattle-global-data:github-nats
      version: 4.3.7
      answers:
        auth.enabled: "false"
        replicaCount: "3"
      name: nats
      targetNamespace: lecex
- name: Config
  steps:
  - applyYamlConfig:
      path: ./rancher/config.yaml
- name: Ui
  steps:
  - applyYamlConfig:
      path: ./rancher/app/ui.yaml
- name: Micro
  steps:
  - applyYamlConfig:
      path: ./rancher/app/micro-rpc.yaml
  - applyYamlConfig:
      path: ./rancher/app/micro-api.yaml
- name: User
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:github-mariadb
      version: 7.3.14
      answers:
        slave.replicas: "3"
        db.name: "user"
      name: mariadb-user
      targetNamespace: lecex
  - applyYamlConfig:
      path: ./rancher/app/user.yaml
  - applyYamlConfig:
      path: ./rancher/app/user-api.yaml
- name: Pay
  steps:
  - applyAppConfig:
    catalogTemplate: cattle-global-data:github-mariadb
    version: 7.3.14
    answers:
      slave.replicas: "3"
      db.name: "pay"
    name: mariadb-pay
    targetNamespace: lecex
  - applyYamlConfig:
      path: ./rancher/app/pay.yaml
  - applyYamlConfig:
      path: ./rancher/app/pay-api.yaml
notification: {}
