stages:
- name: App
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:github-redis
      version: 10.5.7
      answers:
        cluster.slaveCount: "5"
      name: redis
      targetNamespace: lecex
  - applyAppConfig:
      catalogTemplate: cattle-global-data:github-nats
      version: 4.3.7
      answers:
        auth.enabled: "false"
        replicaCount: "5"
      name: nats
      targetNamespace: lecex
  - applyAppConfig:
      catalogTemplate: cattle-global-data:github-mariadb
      version: 7.3.14
      answers:
        slave.replicas: "5"
      name: mariadb
      targetNamespace: lecex
- name: Config
  steps:
  - applyYamlConfig:
      path: ./rancher/config.yaml
- name: Micro
  steps:
  - applyYamlConfig:
      path: ./rancher/app/micro-rpc.yaml
  - applyYamlConfig:
      path: ./rancher/app/micro-api.yaml
- name: User
  steps:
  - applyYamlConfig:
      path: ./rancher/app/user.yaml
  - applyYamlConfig:
      path: ./rancher/app/user-api.yaml
notification: {}
