# 负载均衡
{{ if .Values.app.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: {{ .Values.app.ingress.host }}
    http:
      paths:
        - backend:
            serviceName: app
            servicePort: http
{{ end }}            
---
kind: Service
apiVersion: v1
metadata:
  name: app
spec:
  selector:
    app: app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  {{ if .Values.app.replicaCount }}
  replicas: {{ .Values.app.replicaCount }}
  {{ else }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app 
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            - name: BASE_URL
              value: {{ .Values.app.baseUrl }}
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
