apiVersion: apps/v1
kind: Deployment
metadata:
  name: institution-api
  labels:
    app: institution-api
spec:
  {{ if .Values.institutionApi.replicaCount }}
  replicas: {{ .Values.institutionApi.replicaCount }}
  {{ else }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app: institution-api
  template:
    metadata:
      labels:
        app: institution-api
    spec:
      serviceAccountName: micro-services
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: institution-api
          image: "{{ .Values.institutionApi.image.repository }}:{{ .Values.institutionApi.image.tag }}"
          imagePullPolicy: {{ .Values.institutionApi.image.pullPolicy }}
          command: [
            "institutionApi",
            "--server_address=:8080",
          ]
          env:
            - name: MICRO_REGISTRY
              value: "k8s"
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        - name: health
          image: microhq/health:kubernetes
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=institution-api",
            "--server_address=0.0.0.0:8080"
          ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3