apiVersion: apps/v1
kind: Deployment
metadata:
  name: organize-api
  labels:
    app: organize-api
spec:
  {{ if .Values.organizeApi.replicaCount }}
  replicas: {{ .Values.organizeApi.replicaCount }}
  {{ else }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app: organize-api
  template:
    metadata:
      labels:
        app: organize-api
    spec:
      serviceAccountName: micro-services
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: organize-api
          image: "{{ .Values.organizeApi.image.repository }}:{{ .Values.organizeApi.image.tag }}"
          imagePullPolicy: {{ .Values.organizeApi.image.pullPolicy }}
          command: [
            "organizeApi",
            "--server_address=:8080",
          ]
          env:
            - name: REDIS_HOST
              value: "{{ include "lecex.fullname" . }}-redis-master"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: {{ include "lecex.fullname" . }}-redis
            - name: MICRO_REGISTRY
              value: "k8s"
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        - name: health
          image: microhq/health:kubernetes
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=organize-api",
            "--server_address=0.0.0.0:8080"
          ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3