apiVersion: v1
appVersion: 2.4.1
description: A Helm chart to help backup MySQL databases using mysqldump
home: https://www.mysql.com/
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
keywords:
- mysql
- mysqldump
- backup
maintainers:
- email: username.taken@gmail.com
  name: paulczar
- email: monotek23@gmail.com
  name: monotek
- email: axel.koehler@kiwigrid.com
  name: axdotl
name: mysqldump
sources:
- https://github.com/kubernetes/charts
- https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html
version: 2.6.0
