kind: Service
apiVersion: v1
metadata:
  name: user-api
  namespace: api
spec:
  selector:
    app: user-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: api
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      serviceAccountName: micro-services
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: user-api
          image: registry.cn-hangzhou.aliyuncs.com/lecex/user-api
          imagePullPolicy: Always
          command: [
            "service",
            "--selector=static",
            "--server_address=:8080",
          ]
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: USER_SERVICE
              value: "user.srv:8080"
            - name: REDIS_HOST
              value: "redis-master.api"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: redis
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        - name: health
          image: microhq/health:kubernetes
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=user-api",
            "--server_address=0.0.0.0:8080"
          ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3